
###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}


###
GET http://localhost:8080/api/entrenamientos
Content-Type: application/json



###
GET http://localhost:8080/api/entrenamientos/1
Content-Type: application/json



###
POST http://localhost:8080/api/entrenamientos
Content-Type: application/json

{
  "id": 0,
  "usuarioId": 1,
  "nombre": "nuevo entrenamiento",
  "descripcion": "nuevo descripcion"
}

<> 2025-12-12T103530.201.json

###
PUT http://localhost:8080/api/entrenamientos/3
Content-Type: application/json

{
  "id": 3,
  "usuarioId": 2,
  "nombre": "actualizao",
  "descripcion": "actualizao descripcion"
}

###
DELETE http://localhost:8080/api/entrenamientos/3


###
POST http://localhost:8080/api/auth/logout


###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "oscar",
  "password": "oscar123",
  "email": "oscar@gmail.com",
  "nombre": "oscar",
  "rol": "ADMIN"
}

