
###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "luciaaaaaaaaaa",
  "password": "luciaaaaa1231"
}

<> 2026-02-08T225715.200.json
<> 2026-02-08T224333.200.json
<> 2026-02-08T223502.200.json
<> 2026-02-08T223226.200.json
<> 2026-02-08T220117.200.json
<> 2026-02-08T215154.200.json
<> 2026-02-08T214429.200.json
<> 2026-02-08T213915.200.json
<> 2026-02-07T024453.200.json

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "lucia_amiga",
  "password": "lucia_amiga1234",
  "email": "kdsjsc@dakds.com",
  "nombre": "siuuuuuuu",
  "rol": "ADMIN"
}

<> 2026-02-08T224006.201.json


###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "luciaaaaaaaaaa",
  "password": "luciaaaaa1231",
  "email": "luci1aaaa@gmail.com",
  "nombre": "luciaaaaaaaaaa",
  "rol": "ADMIN"
}

<> 2026-02-08T215132.201.json
<> 2026-02-08T214344.201.json
<> 2026-02-08T213556.201.json
<> 2026-02-08T213450.500.json
<> 2026-02-08T213312.201.json

###
POST http://localhost:8080/api/secretos
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2wiOiJBRE1JTiIsInN1YiI6Imx1Y2lhYWFhYWFhYWFhIiwiaWF0IjoxNzcwNTkyNTE1LCJleHAiOjE3NzA1OTYxMTV9.Zp4YhePp-nZrGX9T5vNQ5xE42BwA5SV7Kj0qya1JWjLYK45Rc4dmc9mMcJLyVJXROEE2nyBjoba-Lg_4SRb6kA
Content-Type: application/json

{
  "contenido": "secretooo",
  "password": "luciaaaaa1231"
}

<> 2026-02-08T223526.201.json
<> 2026-02-08T223306.500.json
<> 2026-02-08T215222.201.txt
<> 2026-02-08T214814.500.json
<> 2026-02-08T214504.401.txt
<> 2026-02-08T214227.401.txt
<> 2026-02-08T214148.401.txt

###
POST http://localhost:8080/api/secretos/1/ver
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2wiOiJBRE1JTiIsInN1YiI6Imx1Y2lhYWFhYWFhYWFhIiwiaWF0IjoxNzcwNTkxOTc4LCJleHAiOjE3NzA1OTU1Nzh9.XJH7iu_uRSN_17PcFFqNNGUXjP2RHjVR1XRZLMAKca3wixiNBvnMvYKKbLiYjaMGQKQhfOuNTT8FDopGzc31Vw
Content-Type: application/json

{
  "password": "luciaaaaa1231"
}

<> 2026-02-08T230117.500.json
<> 2026-02-08T225804.200.json
<> 2026-02-08T224438.200.json
<> 2026-02-08T223555.200.json
<> 2026-02-08T223312.500.json
<> 2026-02-08T220141.500.json
<> 2026-02-08T215358.500.json
<> 2026-02-08T215325.403.json

###
POST http://localhost:8080/api/secretos/1/compartir
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2wiOiJBRE1JTiIsInN1YiI6Imx1Y2lhX2FtaWdhIiwiaWF0IjoxNzcwNTkxODIzLCJleHAiOjE3NzA1OTU0MjN9.0gJfwkMD1028kyHJcqHHG_VerL6eeaMJvRo1G7gp8KahnEu_lJRw9G4qavQWZOxHmoMejcQvLPZTaViiG5egRQ
Content-Type: application/json

{
  "receptorId": 4,
  "password": "lucia_amiga1234"
}

<> 2026-02-08T224215.200.txt

###
DELETE http://localhost:8080/api/secretos/1/compartir/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2wiOiJBRE1JTiIsInN1YiI6Imx1Y2lhX2FtaWdhIiwiaWF0IjoxNzcwNTkxODIzLCJleHAiOjE3NzA1OTU0MjN9.0gJfwkMD1028kyHJcqHHG_VerL6eeaMJvRo1G7gp8KahnEu_lJRw9G4qavQWZOxHmoMejcQvLPZTaViiG5egRQ


<> 2026-02-08T225928.403.json