POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "LUCIIA",
  "password": "TesA3t123456",
  "email": "testA3user2@example.com",
  "nombre": "Usuario de Prueba 3",
  "rol": "ADMIN"
}

###

GET http://localhost:8080/api/auth/activar?codigo= codigodeactivacionn

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "LUCIIA",
  "password": "TesA3t123456"
}

###

GET http://localhost:8080/api/entrenamientos
Authorization: Bearer tokene

###

POST http://localhost:8080/api/entrenamientos
Authorization: Bearer tokene
Content-Type: application/json

{
  "nombre": "Rutina de Fuerza",
  "descripcion": "Entrenamiento de fuerza para principiantes"
}

###

GET http://localhost:8080/api/entrenamientos/1
Authorization: Bearer tokene

###

PUT http://localhost:8080/api/entrenamientos/1
Authorization: Bearer tokene
Content-Type: application/json

{
  "nombre": "Rutina de Fuerza Avanzada",
  "descripcion": "Entrenamiento de fuerza nivel avanzado con pesas"
}

###

DELETE http://localhost:8080/api/entrenamientos/1
Authorization: Bearer tokene

###

POST http://localhost:8080/api/auth/2fa/enable
Authorization: Bearer tokene

###

POST http://localhost:8080/api/auth/2fa/confirm
Authorization: Bearer tokene
Content-Type: application/json

{
  "code": "123456"
}

###

GET http://localhost:8080/api/auth/2fa/status
Authorization: Bearer tokene

###

POST http://localhost:8080/api/auth/logout

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "LUCIIA",
  "password": "TesA3t123456"
}

###

POST http://localhost:8080/api/auth/2fa/verify
Content-Type: application/json

{
  "username": "LUCIIA",
  "codigo": "123456"
}

###

GET http://localhost:8080/api/entrenamientos
Authorization: Bearer tokene

###

POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "refresh"
}

###

POST http://localhost:8080/api/auth/2fa/disable
Authorization: Bearer tokene

###

GET http://localhost:8080/api/auth/2fa/status
Authorization: Bearer tokene

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "LUCIIA",
  "password": "TesA3t123456"
}

###

GET http://localhost:8080/api/entrenamientos

###

GET http://localhost:8080/api/entrenamientos
Authorization: Bearer tokenmalo

###

POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "refresjhmalo"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "LUCIIA",
  "password": "password_incorrecta"
}

###

GET http://localhost:8080/api/entrenamientos/999999
Authorization: Bearer tokene

