POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123",
  "email": "admin@example.com",
  "nombre": "Administrador",
  "rol": "ADMIN"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###

GET http://localhost:8080/api/entrenamientos
Authorization: Bearer tokene

###

POST http://localhost:8080/api/auth/2fa/enable
Authorization: Bearer tokene

###

POST http://localhost:8080/api/auth/2fa/confirm
Authorization: Bearer tokene
Content-Type: application/json

{
  "code": "123456"
}

###

GET http://localhost:8080/api/auth/2fa/status
Authorization: Bearer tokene

###

POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "refresh"
}

###

POST http://localhost:8080/api/auth/2fa/disable
Authorization: Bearer tokene

###

POST http://localhost:8080/api/auth/logout

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###

POST http://localhost:8080/api/auth/2fa/verify
Content-Type: application/json

{
  "username": "admin",
  "codigo": "123456"
}

###

GET http://localhost:8080/api/entrenamientos

###

GET http://localhost:8080/api/entrenamientos
Authorization: Bearer tokenemalo

###

POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "token_invalido"
}

###

GET http://localhost:8080/api/entrenamientos
Authorization: Bearer tokene

