package com.example.navigationcompose.common

object Constantes {
    const val ERROR_DEL_SERVIDOR = "Error del servidor: "
    const val ERROR_DE_CONEXION = "Error de conexión: "
    const val ERROR_DE_RED = "Error de red: "
    const val ERROR_FALLO_CONEXION = "Fallo de conexión: "
    const val ERROR_USUARIO_PASSWORD_INCORRECTOS = "Usuario o contraseña incorrectos"
    const val ERROR_USUARIO_EMAIL_EXISTEN = "El usuario o email ya existen"
    const val ERROR_NO_CARGAR_ENTRENAMIENTOS = "No se pudieron cargar los entrenamientos"
    const val ERROR_ENTRENAMIENTO_NO_ENCONTRADO = "Entrenamiento no encontrado"
    const val ERROR_BUSCAR_DETALLE = "Error al buscar detalle"
    const val ERROR_GUARDAR_SERVIDOR = "Error al guardar en el servidor"
    const val ERROR_FALLO_RED = "Fallo de red"
    const val ERROR_NO_ELIMINAR = "No se pudo eliminar"
    const val ERROR_CARGAR_EJERCICIOS = "Error al cargar lista de ejercicios"
    const val ERROR_GENERICO = "Error: "
    const val ERROR_PAGE_NUMBER = "Page number must be non-negative"
    const val URL_CHARACTERS = "characters"

    const val ID = "id"
    const val PAGE = "page"

    const val API_AUTH_LOGIN = "api/auth/login"
    const val API_AUTH_REGISTER = "api/auth/register"
    const val API_ENTRENAMIENTOS = "api/entrenamientos"
    const val API_ENTRENAMIENTOS_ID = "api/entrenamientos/{id}"
    const val API_EJERCICIOS = "api/ejercicios"

    const val RETROFIT_GYMAPI = "GymRetrofit"
    const val RETROFIT_DBAPI = "DragonBallRetrofit"

    const val ITEMS = "items"

    const val PREFS_NAME = "prefs_seguras"
    const val PREF_ACCESS_TOKEN = "access_token"
    const val PREF_REFRESH_TOKEN = "refresh_token"

    const val TEXT_APP_NAME = "GYM APP"
    const val TEXT_LABEL_USUARIO = "Usuario"
    const val TEXT_LABEL_PASSWORD = "Contraseña"
    const val TEXT_BUTTON_LOGIN = "ENTRAR"
    const val TEXT_NO_ACCOUNT = "¿No tienes cuenta? Regístrate aquí"
    const val TEXT_USUARIO_EJEMPLO = "UsuarioEjemplo"

    const val TEXT_TITULO_REGISTRO = "Registro"
    const val TEXT_CREAR_CUENTA = "Crear Cuenta"
    const val TEXT_LABEL_EMAIL = "Email"
    const val TEXT_LABEL_NOMBRE_COMPLETO = "Nombre completo"
    const val TEXT_LABEL_CONFIRMAR_PASSWORD = "Confirmar contraseña"
    const val TEXT_BUTTON_REGISTRARSE = "REGISTRARSE"
    const val TEXT_DESCRIPCION_VOLVER = "Volver"

    const val TEXT_NOMBRE_ENTRENAMIENTO = "Nombre Entrenamiento"
    const val TEXT_DESCRIPCION = "Descripción"
    const val TEXT_BUTTON_CREAR = "CREAR"
    const val TEXT_BUTTON_ACTUALIZAR = "ACTUALIZAR"
    const val TEXT_RUTINA_EJEMPLO = "Rutina A"
    const val TEXT_NOTAS_PROGRESION = "Notas sobre la progresión de cargas para esta semana."
    const val TEXT_EJERCICIOS_RUTINA = "Ejercicios de esta rutina"

    const val TEXT_EMPUJE = "Empuje (Pecho/Tríceps)"
    const val TEXT_TRACCION = "Tracción (Espalda/Bíceps)"
    const val TEXT_PIERNA = "Pierna Completa"
    const val TEXT_ENFOQUE_FUERZA = "Enfoque en fuerza"
    const val TEXT_HIPERTROFIA = "Hipertrofia"
    const val TEXT_DIA_PESADO = "Día pesado"

    const val URL_BASE_EMULATOR = "http://10.0.2.2:8080"

    const val TEXT_YA_TIENE_CUENTA = "¿Ya tienes cuenta? Inicia sesión"
    const val TEXT_OCULTAR_PASSWORD = "Ocultar contraseña"
    const val TEXT_MOSTRAR_PASSWORD = "Mostrar contraseña"
    const val USER = "USER"
    const val TEXT_PERSONAJES_DRAGON_BALL = "Personajes Dragon Ball"
    const val TEXT_RAZA = "Raza: "
    const val TEXT_KI = "Ki: "
    const val TEXT_HERO = "Hero"
    const val TEXT_VILLAIN = "Villain"
    const val TEXT_GOKU = "Goku"
    const val TEXT_FREEZER = "Freezer"
    const val TEXT_SAIYAN = "Saiyan"
    const val TEXT_FRIEZA_RACE = "Frieza Race"
    const val TEXT_KI_GOKU = "60.000.000"
    const val TEXT_KI_FREEZER = "120.000.000"
    const val URL_EXAMPLE_GOKU_GIF = "https://example.com/goku.gif"
    const val URL_EXAMPLE_FREEZER_GIF = "https://example.com/freezer.gif"

    // ========== TEXTOS UI - HOME ==========
    const val TEXT_GYM = "Gym"
    const val TEXT_DRAGON_BALL = "DragonBall"
    const val TEXT_SALIR = "Salir"
    const val TEXT_BIENVENIDO = "¡BIENVENIDO!"
    const val TEXT_NO_SESIONES_RECIENTES = "No hay sesiones recientes"
    const val TEXT_PERFIL = "Perfil"
    const val TEXT_CONTENIDO_PANTALLA = "Contenido de la pantalla seleccionada"

    // ========== AUTH ==========
    const val AUTH_HEADER = "Authorization"
    const val AUTH_BEARER_PREFIX = "Bearer "

    const val ERROR_PASSWORDS_NO_COINCIDEN = "Las contraseñas no coinciden"
    const val ERROR_PASSWORD_VACIA = "La contraseña no puede estar vacía"
    const val ERROR_DESCONOCIDO = "Error desconocido"
    const val REGISTRO_EXITOSO = "¡Registro completado con éxito!"
    const val REGISTRO_EXITOSO_MENSAJE = "Registro completado con éxito! Activa tu cuenta desde el email y logueate"
}
