# ENTRENAMIENTOS - ADMIN

### (ADMIN) Crear entrenamiento
POST http://localhost:8080/api/entrenamientos
Content-Type: application/json

{
  "usuarioId": 1,
  "nombre": "Entrenamiento Pecho",
  "descripcion": "Series de banca"
}

### (ADMIN) Ver todos los entrenamientos
GET http://localhost:8080/api/entrenamientos

### (ADMIN) entrenamiento por id
GET http://localhost:8080/api/entrenamientos/1


### (ADMIN) Actualizar entrenamiento
PUT http://localhost:8080/api/entrenamientos/1
Content-Type: application/json

{
  "id": 1,
  "usuarioId": 1,
  "nombre": "Entrenamiento Pecho Actualizado",
  "descripcion": "Modificado"
}

### (ADMIN) Borrar entrenamiento
DELETE http://localhost:8080/api/entrenamientos/3



#ENTRENAMIENTOS - USER

### (USER) Ver SOLO sus entrenamientos
GET http://localhost:8080/api/entrenamientos

### (USER)  entrenamiento propio por id
GET http://localhost:8080/api/entrenamientos/2


### (USER) Borrar su propio entrenamiento (DEBE PERMITIR)
DELETE http://localhost:8080/api/entrenamientos/2

