spring.application.name=EmailSpring
spring.datasource.url=jdbc:h2:file:./data/gymdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root

server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#docker -d -p 1025:1025 -p 8025:8025 mailhog/mailhog
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false